[package]
edition = "2018"
readme = "README.md"
name = "app"
version = "0.1.0"

[dependencies]
cortex-m = "0.7.2"
cortex-m-rt = "0.6.10"
panic-halt = "0.2.0"
nrf52840-hal = "0.12.2"

[profile.dev]
opt-level = 's'
codegen-units = 1 
lto = true 

[profile.release]
codegen-units = 1 
lto = true 
