[package]
name = "common"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.126", default-features = false }
serde_derive = "1.0.126"

[dev-dependencies]
postcard = { version = "0.7.0", features = ["use-std"] }